### ISSUE TITLE
Help needed with ROM structure

### ISSUE THREAD

**Issue by gmarty** [gzip/nes-6502-maniac-mansion-decoded#1]
Hi! That's a great project.
I'm currently developing [SCUMM NES](https://github.com/gmarty/scumm-nes), am app to view the resources of Maniac Mansion on NES.
I started working on changing the ROM with the goal to make it a complete editor. I'm blocked by the space limitation and I'd like to reuse some of your approach in moving the content around.

I'd love to talk with you about how to work around the limitations. What's the easiest way to talk to you? Do you use Discord?

**Comment by gzip** [comment]
I don't use Discord much but I do have an account. You can also try me on romhacking.net.

**Comment by gmarty** [comment]
Yes, I've got an account:
https://www.romhacking.net/community/8594/

Forum account:
https://www.romhacking.net/forum/index.php?action=profile;u=191358

**Comment by gzip** [comment]
I've DM'd you on romhacking.net.
